-- Ad impression/click event log — powers the per-ad "Detailed Analytics"
-- view (daily trend, traffic sources, geography). Additive + idempotent.
-- Run manually (the user runs ALL DB commands):
--   $env:ALLOW_PROD_DB_WRITE="1"; node scripts/run-migration.mjs docs/ad-events-migration.sql

CREATE TABLE IF NOT EXISTS ad_events (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ad_type text NOT NULL,
  ad_id text NOT NULL,
  event_type text NOT NULL,
  source text,
  country text,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ad_events_lookup_idx ON ad_events (ad_type, ad_id, created_at);
