-- Creator codes — storewide affiliate/referral codes (distinct from coupons):
-- a buyer gets a discount, the creator earns a commission, tracked here.
-- Additive + idempotent. Run manually (the user runs ALL DB commands):
--   $env:ALLOW_PROD_DB_WRITE="1"; node scripts/run-migration.mjs docs/creator-codes-migration.sql

CREATE TABLE IF NOT EXISTS creator_codes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  created_by text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  discount_type discount_type NOT NULL,
  discount_value numeric(10, 2) NOT NULL,
  commission_type discount_type NOT NULL,
  commission_value numeric(10, 2) NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  used_count integer NOT NULL DEFAULT 0,
  created_at timestamp DEFAULT now(),
  updated_at timestamp DEFAULT now()
);

CREATE TABLE IF NOT EXISTS creator_code_redemptions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  creator_code_id integer NOT NULL REFERENCES creator_codes(id) ON DELETE CASCADE,
  user_id text REFERENCES users(id),
  order_id integer REFERENCES orders(id),
  discount_amount numeric(10, 2) NOT NULL,
  commission_amount numeric(10, 2) NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE orders ADD COLUMN IF NOT EXISTS creator_code_id integer REFERENCES creator_codes(id);
