-- Site content — admin-editable marketing copy (home page hero/why-choose-us/
-- ecosystem/FAQ text). One row per named section; `value` holds the whole
-- JSON shape so new fields never need another migration.
-- Additive + idempotent. Run manually (the user runs ALL DB commands):
--   $env:ALLOW_PROD_DB_WRITE="1"; node scripts/run-migration.mjs docs/site-content-migration.sql

CREATE TABLE IF NOT EXISTS site_content (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key text NOT NULL UNIQUE,
  value json NOT NULL,
  updated_at timestamp DEFAULT now()
);
